from app.models import db, hike_keywords
from sqlalchemy import insert

def seed_hike_keywords():
    db.session.execute(hike_keywords.insert().values(hike_id=1, keyword_id=1))
    db.session.execute(hike_keywords.insert().values(hike_id=1, keyword_id=2))
    db.session.execute(hike_keywords.insert().values(hike_id=1, keyword_id=3))
    db.session.execute(hike_keywords.insert().values(hike_id=1, keyword_id=4))
    db.session.execute(hike_keywords.insert().values(hike_id=1, keyword_id=5))
    db.session.execute(hike_keywords.insert().values(hike_id=1, keyword_id=6))
    db.session.execute(hike_keywords.insert().values(hike_id=2, keyword_id=1))
    db.session.execute(hike_keywords.insert().values(hike_id=2, keyword_id=2))
    db.session.execute(hike_keywords.insert().values(hike_id=2, keyword_id=3))
    db.session.execute(hike_keywords.insert().values(hike_id=2, keyword_id=4))
    db.session.execute(hike_keywords.insert().values(hike_id=2, keyword_id=5))
    db.session.execute(hike_keywords.insert().values(hike_id=2, keyword_id=6))
    db.session.execute(hike_keywords.insert().values(hike_id=3, keyword_id=1))
    db.session.execute(hike_keywords.insert().values(hike_id=3, keyword_id=2))
    db.session.execute(hike_keywords.insert().values(hike_id=3, keyword_id=3))
    db.session.execute(hike_keywords.insert().values(hike_id=3, keyword_id=4))
    db.session.execute(hike_keywords.insert().values(hike_id=3, keyword_id=5))
    db.session.execute(hike_keywords.insert().values(hike_id=3, keyword_id=6))
    db.session.execute(hike_keywords.insert().values(hike_id=4, keyword_id=1))
    db.session.execute(hike_keywords.insert().values(hike_id=4, keyword_id=2))
    db.session.execute(hike_keywords.insert().values(hike_id=4, keyword_id=3))
    db.session.execute(hike_keywords.insert().values(hike_id=4, keyword_id=4))
    db.session.execute(hike_keywords.insert().values(hike_id=4, keyword_id=5))
    db.session.execute(hike_keywords.insert().values(hike_id=4, keyword_id=6))
    db.session.execute(hike_keywords.insert().values(hike_id=5, keyword_id=5))
    db.session.execute(hike_keywords.insert().values(hike_id=5, keyword_id=6))
    db.session.execute(hike_keywords.insert().values(hike_id=5, keyword_id=7))
    db.session.execute(hike_keywords.insert().values(hike_id=5, keyword_id=8))
    db.session.execute(hike_keywords.insert().values(hike_id=5, keyword_id=9))
    db.session.execute(hike_keywords.insert().values(hike_id=5, keyword_id=10))
    db.session.execute(hike_keywords.insert().values(hike_id=6, keyword_id=5))
    db.session.execute(hike_keywords.insert().values(hike_id=6, keyword_id=6))
    db.session.execute(hike_keywords.insert().values(hike_id=6, keyword_id=7))
    db.session.execute(hike_keywords.insert().values(hike_id=6, keyword_id=8))
    db.session.execute(hike_keywords.insert().values(hike_id=6, keyword_id=9))
    db.session.execute(hike_keywords.insert().values(hike_id=6, keyword_id=10))
    db.session.execute(hike_keywords.insert().values(hike_id=7, keyword_id=8))
    db.session.execute(hike_keywords.insert().values(hike_id=7, keyword_id=9))
    db.session.execute(hike_keywords.insert().values(hike_id=7, keyword_id=10))
    db.session.execute(hike_keywords.insert().values(hike_id=7, keyword_id=11))
    db.session.execute(hike_keywords.insert().values(hike_id=7, keyword_id=12))
    db.session.execute(hike_keywords.insert().values(hike_id=7, keyword_id=13))
    db.session.execute(hike_keywords.insert().values(hike_id=8, keyword_id=1))
    db.session.execute(hike_keywords.insert().values(hike_id=8, keyword_id=3))
    db.session.execute(hike_keywords.insert().values(hike_id=8, keyword_id=5))
    db.session.execute(hike_keywords.insert().values(hike_id=8, keyword_id=8))
    db.session.execute(hike_keywords.insert().values(hike_id=8, keyword_id=9))
    db.session.execute(hike_keywords.insert().values(hike_id=8, keyword_id=13))
    db.session.execute(hike_keywords.insert().values(hike_id=9, keyword_id=12))
    db.session.execute(hike_keywords.insert().values(hike_id=9, keyword_id=13))
    db.session.execute(hike_keywords.insert().values(hike_id=9, keyword_id=14))
    db.session.execute(hike_keywords.insert().values(hike_id=9, keyword_id=15))
    db.session.execute(hike_keywords.insert().values(hike_id=9, keyword_id=16))
    db.session.execute(hike_keywords.insert().values(hike_id=9, keyword_id=9))
    db.session.execute(hike_keywords.insert().values(hike_id=10, keyword_id=11))
    db.session.execute(hike_keywords.insert().values(hike_id=10, keyword_id=10))
    db.session.execute(hike_keywords.insert().values(hike_id=10, keyword_id=12))
    db.session.execute(hike_keywords.insert().values(hike_id=10, keyword_id=14))
    db.session.execute(hike_keywords.insert().values(hike_id=10, keyword_id=4))
    db.session.execute(hike_keywords.insert().values(hike_id=10, keyword_id=2))




    db.session.commit()


def undo_hike_keywords():
    db.session.execute('TRUNCATE hike_keywords RESTART IDENTITY CASCADE;')
    db.session.commit()