"""added Park model and seeder

Revision ID: 1a1448ae4a25
Revises: ffdc0a98111c
Create Date: 2021-12-14 13:58:17.038455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a1448ae4a25'
down_revision = 'ffdc0a98111c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('parks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('park_name', sa.String(length=50), nullable=False),
    sa.Column('lat', sa.Float(precision=32, asdecimal=True), nullable=False),
    sa.Column('long', sa.Float(precision=32, asdecimal=True), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('country', sa.String(length=40), nullable=False),
    sa.Column('state', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parks')
    # ### end Alembic commands ###
