"""add_Photo_model_and_seeder

Revision ID: 98edb5f27fa4
Revises: 07f1a8fab5e3
Create Date: 2021-12-14 16:50:23.459245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98edb5f27fa4'
down_revision = '07f1a8fab5e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('hike_id', sa.Integer(), nullable=False),
    sa.Column('img_url', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['hike_id'], ['hikes.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('photos')
    # ### end Alembic commands ###
