"""add_Hike_model_and_seeder

Revision ID: 07f1a8fab5e3
Revises: 1a1448ae4a25
Create Date: 2021-12-14 15:19:45.390573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07f1a8fab5e3'
down_revision = '1a1448ae4a25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hikes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hike_name', sa.String(length=50), nullable=False),
    sa.Column('park_id', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(precision=32, asdecimal=True), nullable=False),
    sa.Column('long', sa.Float(precision=32, asdecimal=True), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('length', sa.Integer(), nullable=False),
    sa.Column('eta', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.String(length=15), nullable=False),
    sa.ForeignKeyConstraint(['park_id'], ['parks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hikes')
    # ### end Alembic commands ###
